[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd backend",
  "npm install --legacy-peer-deps"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd backend",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"
